apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
  namespace: testargo3
spec:
  containers:
  - image: nginx
    name: test
    command:
    - sleep
    - "3600"
