apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
  namespace: testargo3
spec:
  containers:
  - image: nginx
    name: test
    command:
    - sleep
    - "3600"
------------------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-nginx
  name: service-nginx
spec:
  ports:
  - name: nginx
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: test
  type: ClusterIP
  
