apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-ns
  name: my-ns
spec:
  ports:
  - name: one
    port: 5678
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-ns
  type: ClusterIP
