apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
      app: nginx
      tier: frontend
  ports:
    - port: 80 ### Mandatory ###
      targetPort: 80
      nodePort: 30008
