apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-nginx
  name: service-nginx
spec:
  ports:
  - name: nginx
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: test
  type: ClusterIP
